version: '3.9'

services:

  # ================= CONFIG / DISCOVERY =================

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on:
      - config-server

  gateway:
    build: ./api-gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service

  # ================= INFRAESTRUCTURA =================

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  # ================= PRODUCT (MongoDB) =================

  mongo-product:
    image: mongo:6.0
    container_name: mongo-product
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: product_user
      MONGO_INITDB_ROOT_PASSWORD: Product123
      MONGO_INITDB_DATABASE: ecommerce_product
    ports:
      - "27017:27017"

  product:
    build: ./product-service
    container_name: product-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://product_user:Product123@mongo-product:27017/ecommerce_product?authSource=admin
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - mongo-product

  # ================= INVENTORY (Postgres) =================

  postgres-inventory:
    image: postgres:16
    container_name: postgres-inventory
    restart: always
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: InventoryPass123!
    ports:
      - "5436:5432"

  inventory:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-inventory:5432/inventory_db
      - SPRING_DATASOURCE_USERNAME=inventory_user
      - SPRING_DATASOURCE_PASSWORD=InventoryPass123!
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - postgres-inventory
      - rabbitmq

  # ================= CART (Redis only) =================

  cart:
    build: ./cart-service
    container_name: cart-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_RABBITMQ_HOST=rabbitmq
      - PRODUCT_SERVICE_URL=http://product-service:8081
      - INVENTORY_SERVICE_URL=http://inventory-service:8084
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - redis-cache

  # ================= ORDER (SQL Server) =================
  
  sqlserver-order:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-order
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "TuPasswordFuerte123!"
      MSSQL_PID: Express
    ports:
      - "1435:1433"
    # Este healthcheck crea la base de datos "orderdb" si no existe.
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'TuPasswordFuerte123!' -C -Q \"IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'orderdb') BEGIN CREATE DATABASE orderdb; END\" && /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'TuPasswordFuerte123!' -C -Q \"SELECT 1\""]
      interval: 10s
      timeout: 10s
      retries: 10

  order:
    build: ./order-service
    container_name: order-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # Conexión directa a SQL Server sobreescribiendo la configuración local
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver-order:1433;databaseName=orderdb;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=TuPasswordFuerte123!
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_REDIS_HOST=redis-cache
      - CUSTOMER_SERVICE_URL=http://customer-service:8085
      - INVENTORY_SERVICE_URL=http://inventory-service:8084
      - PRICING_SERVICE_URL=http://pricing-service:8090
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      sqlserver-order:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  # ================= CUSTOMER =================

  postgres-customer:
    image: postgres:16
    container_name: postgres-customer
    restart: always
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: customer_user
      POSTGRES_PASSWORD: CustomerPass123!
    ports:
      - "5437:5432"

  customer:
    build: ./customer-service
    container_name: customer-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-customer:5432/customer_db
      - SPRING_DATASOURCE_USERNAME=customer_user
      - SPRING_DATASOURCE_PASSWORD=CustomerPass123!
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - postgres-customer

  # ================= PRICING =================

  postgres-pricing:
    image: postgres:16
    container_name: postgres-pricing
    restart: always
    environment:
      POSTGRES_DB: pricing_db
      POSTGRES_USER: pricing_user
      POSTGRES_PASSWORD: PricingPass123!
    ports:
      - "5438:5432"

  pricing:
    build: ./pricing-service
    container_name: pricing-service
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-pricing:5432/pricing_db
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - postgres-pricing

  # ================= PAYMENT =================

  postgres-payment:
    image: postgres:16
    container_name: postgres-payment
    restart: always
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: PaymentPass123!
    ports:
      - "5439:5432"

  payment:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8092:8092"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-payment:5432/payment_db
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - postgres-payment

  # ================= SHIPPING =================

  postgres-shipping:
    image: postgres:16
    container_name: postgres-shipping
    restart: always
    environment:
      POSTGRES_DB: shipping_db
      POSTGRES_USER: shipping_user
      POSTGRES_PASSWORD: ShippingPass123!
    ports:
      - "5440:5432"

  shipping:
    build: ./shipping-service
    container_name: shipping-service
    ports:
      - "8091:8091"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-shipping:5432/shipping_db
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_REDIS_HOST=redis-cache
      - CUSTOMER_SERVICE_URL=http://customer-service:8085
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - postgres-shipping

  # ================= NOTIFICATION =================

  notification:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8089:8089"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - rabbitmq

volumes:
  redis-data: