version: '3.9'

networks:
  ecommerce-net:
    driver: bridge

services:

  # ==========================================
  # 1. INFRAESTRUCTURA CORE (Discovery & Config)
  # ==========================================

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - ecommerce-net

  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on:
      - config-server
    networks:
      - ecommerce-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_HOST=discovery-service
    depends_on:
      - config-server
      - discovery-service
    networks:
      - ecommerce-net

  # ==========================================
  # 2. BROKERS Y CACHÉ
  # ==========================================

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-net

  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - ecommerce-net
    volumes:
      - redis-data:/data

  # ==========================================
  # 3. BASES DE DATOS
  # ==========================================

  mongo-product:
    image: mongo:6.0
    container_name: mongo-product
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: product_user
      MONGO_INITDB_ROOT_PASSWORD: Product123
      MONGO_INITDB_DATABASE: ecommerce_product
    ports:
      - "27017:27017"
    networks:
      - ecommerce-net

  postgres-inventory:
    image: postgres:16
    container_name: postgres-inventory
    restart: always
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: InventoryPass123!
    ports:
      - "5436:5432"
    networks:
      - ecommerce-net

  sqlserver-order:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-order
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "TuPasswordFuerte123!"
      MSSQL_PID: Express
    ports:
      - "1435:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'TuPasswordFuerte123!' -C -Q \"IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'orderdb') BEGIN CREATE DATABASE orderdb; END\" && /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'TuPasswordFuerte123!' -C -Q \"SELECT 1\""]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - ecommerce-net

  postgres-customer:
    image: postgres:16
    container_name: postgres-customer
    restart: always
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: customer_user
      POSTGRES_PASSWORD: CustomerPass123!
    ports:
      - "5437:5432"
    networks:
      - ecommerce-net

  postgres-pricing:
    image: postgres:16
    container_name: postgres-pricing
    restart: always
    environment:
      POSTGRES_DB: pricing_db
      POSTGRES_USER: pricing_user
      POSTGRES_PASSWORD: PricingPass123!
    ports:
      - "5438:5432"
    networks:
      - ecommerce-net

  postgres-payment:
    image: postgres:16
    container_name: postgres-payment
    restart: always
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: PaymentPass123!
    ports:
      - "5439:5432"
    networks:
      - ecommerce-net

  postgres-shipping:
    image: postgres:16
    container_name: postgres-shipping
    restart: always
    environment:
      POSTGRES_DB: shipping_db
      POSTGRES_USER: shipping_user
      POSTGRES_PASSWORD: ShippingPass123!
    ports:
      - "5440:5432"
    networks:
      - ecommerce-net

  # ==========================================
  # 4. MICROSERVICIOS DE NEGOCIO
  # ==========================================

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - DB_HOST=mongo-product
      - REDIS_HOST=redis-cache
      - RABBITMQ_HOST=rabbitmq
      - EUREKA_HOST=discovery-service
    depends_on:
      - config-server
      - discovery-service
      - mongo-product
      - rabbitmq
    networks:
      - ecommerce-net

  cart-service:
    build: ./cart-service
    container_name: cart-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - REDIS_HOST=redis-cache
      - RABBITMQ_HOST=rabbitmq
      - EUREKA_HOST=discovery-service
    depends_on:
      - config-server
      - discovery-service
      - redis-cache
    networks:
      - ecommerce-net

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - DB_HOST=sqlserver-order
      - REDIS_HOST=redis-cache
      - RABBITMQ_HOST=rabbitmq
      - EUREKA_HOST=discovery-service
    depends_on:
      config-server:
        condition: service_started
      discovery-service:
        condition: service_started
      rabbitmq:
        condition: service_started
      sqlserver-order:
        condition: service_healthy
    networks:
      - ecommerce-net

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - DB_HOST=postgres-inventory
      - REDIS_HOST=redis-cache
      - RABBITMQ_HOST=rabbitmq
      - EUREKA_HOST=discovery-service
    depends_on:
      - config-server
      - discovery-service
      - postgres-inventory
      - rabbitmq
    networks:
      - ecommerce-net

  customer-service:
    build: ./customer-service
    container_name: customer-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - DB_HOST=postgres-customer
      - REDIS_HOST=redis-cache
      - RABBITMQ_HOST=rabbitmq
      - EUREKA_HOST=discovery-service
    depends_on:
      - config-server
      - discovery-service
      - postgres-customer
    networks:
      - ecommerce-net

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8089:8089"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - REDIS_HOST=redis-cache
      - RABBITMQ_HOST=rabbitmq
      - EUREKA_HOST=discovery-service
    depends_on:
      - config-server
      - discovery-service
      - rabbitmq
      - redis-cache
    networks:
      - ecommerce-net

  pricing-service:
    build: ./pricing-service
    container_name: pricing-service
    ports:
      - "8090:8090"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - DB_HOST=postgres-pricing
      - REDIS_HOST=redis-cache
      - RABBITMQ_HOST=rabbitmq
      - EUREKA_HOST=discovery-service
    depends_on:
      - config-server
      - discovery-service
      - postgres-pricing
      - redis-cache
    networks:
      - ecommerce-net

  shipping-service:
    build: ./shipping-service
    container_name: shipping-service
    ports:
      - "8091:8091"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - DB_HOST=postgres-shipping
      - REDIS_HOST=redis-cache
      - RABBITMQ_HOST=rabbitmq
      - EUREKA_HOST=discovery-service
    depends_on:
      - config-server
      - discovery-service
      - postgres-shipping
      - rabbitmq
    networks:
      - ecommerce-net

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8092:8092"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - DB_HOST=postgres-payment
      - REDIS_HOST=redis-cache
      - RABBITMQ_HOST=rabbitmq
      - EUREKA_HOST=discovery-service
    depends_on:
      - config-server
      - discovery-service
      - postgres-payment
      - rabbitmq
    networks:
      - ecommerce-net

volumes:
  redis-data: